<a href="https://colab.research.google.com/github/shawn-odonnell/hello-world/blob/master/np_ndarray_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy arrays
Here are some exercises to remind myself what exactly they are and what the notation means

In [0]:
from platform import python_version
print(f"Using python version {python_version()}")
import numpy as np
print(f"Using numpy version {np.__version__}")

Using python version 3.6.9
Using numpy version 1.17.5


In [0]:
info = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print("With the code \"info = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])\" you can create an array called \'info\'.")
print(f"The type() of the array structure is {type(info)}")
print("Here's what that array looks like if you just print() it:")
print(info)
print(f"The '.shape' of the array is {info.shape}.")
print(f"The number of dimensions, '.ndim', in the array is {info.ndim}.")
print(f"The array takes up '.nbytes' bytes of memory: {info.nbytes}.")
print(f"The .dtype of the array is {info.dtype}.")


With the code "info = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])" you can create an array called 'info'.
The type() of the array structure is <class 'numpy.ndarray'>
Here's what that array looks like if you just print() it:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The '.shape' of the array is (3, 3).
The number of dimensions, '.ndim', in the array is 2.
The array takes up '.nbytes' bytes of memory: 72.
The .dtype of the array is int64.


In [0]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([[1, 2, 3]])

print(vector1.shape)
print(vector2.shape)


(3,)
(1, 3)


In [0]:
# creating a multidimensional array with random integers
np.random.seed(0) # any seed will do; manual set makes results reproducible
print("Making 'randArray' with code: \"randArray = np.random.randint(0, 10, size=(2, 5, 5))\".")
randArray = np.random.randint(0, 10, size=(2, 5, 5))
print(f"The type of 'randArray' is {type(randArray)}.")
print(f"The shape of the array is {randArray.shape}.")
print(f"The size of 'randArray' is {randArray.size} elements.")
print(f"The elements of 'randArray' are of type {randArray.dtype}.")
print(f"The total number of bytes taken up by 'randArray' ({randArray.nbytes}) is\n",
      f"the number of elements ({randArray.size}) times the size of each element ({randArray.itemsize}).")
print(f"\nAnd 'randArray' looks like this:\n")
print(randArray)
print("\nLooking at selections from the array:")
print(f"{randArray[1]}, which is of type {type(randArray[1])} and shape {randArray[1].shape}.")
print(f"{randArray[1,1]}, which is of type {type(randArray[1,1])} and shape {randArray[1,1].shape}.")
print(f"{randArray[1,1,2]}, which is of type {type(randArray[1,1,2])} and has no shape.")

Making 'randArray' with code: "randArray = np.random.randint(0, 10, size=(2, 5, 5))".
The type of 'randArray' is <class 'numpy.ndarray'>.
The shape of the array is (2, 5, 5).
The size of 'randArray' is 50 elements.
The elements of 'randArray' are of type int64.
The total number of bytes taken up by 'randArray' (400) is
 the number of elements (50) times the size of each element (8).

And 'randArray' looks like this:

[[[5 0 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]
  [5 9 8 9 4]]

 [[3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]
  [9 9 0 4 7]
  [3 2 7 2 0]]]

Looking at selections from the array:
[[3 0 3 5 0]
 [2 3 8 1 3]
 [3 3 7 0 1]
 [9 9 0 4 7]
 [3 2 7 2 0]], which is of type <class 'numpy.ndarray'> and shape (5, 5).
[2 3 8 1 3], which is of type <class 'numpy.ndarray'> and shape (5,).
8, which is of type <class 'numpy.int64'> and has no shape.


In [0]:
# pick out just the center of the first subarray. That is, pull out
# element 0 on the first index, and elements with indices 1 through 4-1 on 
# the other two dimensions
randArray[0,1:4,1:4] 
# I can reshape the array 
newArray = randArray.reshape(5,2,5)
print(newArray)
offsizeArray = randArray.reshape((1, randArray.size))
print("\n")
print(offsizeArray)
offsizeArray.shape
offsizeArray[:,35]

[[[5 0 3 3 7]
  [9 3 5 2 4]]

 [[7 6 8 8 1]
  [6 7 7 8 1]]

 [[5 9 8 9 4]
  [3 0 3 5 0]]

 [[2 3 8 1 3]
  [3 3 7 0 1]]

 [[9 9 0 4 7]
  [3 2 7 2 0]]]


[[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6 7 7 8 1 5 9 8 9 4 3 0 3 5 0 2 3 8 1 3 3
  3 7 0 1 9 9 0 4 7 3 2 7 2 0]]


array([3])

## numpy.newaxis
Adds dimensions, as in when you go from a one-dimensional array to a two-dimensional column vector or row vector.

In [0]:
a = np.array([1, 2, 3])
print(f"a is\n{a}")
print(f"a's shape is {a.shape}")
print(f"a's dimensionality is {a.ndim}")
b = a[:, np.newaxis]
print(f"b is \n{b}")
print(f"b's shape is {b.shape}")
print(f"b's dimensionality is {b.ndim}")
c = a[np.newaxis,:]
print(f"c is \n{c}")
print(f"c's shape is {c.shape}")
print(f"c's dimensionality is {c.ndim}")

a is
[1 2 3]
a's shape is (3,)
a's dimensionality is 1
b is 
[[1]
 [2]
 [3]]
b's shape is (3, 1)
b's dimensionality is 2
c is 
[[1 2 3]]
c's shape is (1, 3)
c's dimensionality is 2
